import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { 
  ScrollText, 
  Search, 
  Filter, 
  AlertTriangle, 
  CheckCircle, 
  Info, 
  Download,
  RefreshCw
} from "lucide-react";

export default function SystemLogsPage() {
  const [logs] = useState([
    { id: 1, level: "error", source: "Twilio Webhook", message: "Signature validation failed for incoming call", timestamp: "2024-12-01 10:42:12", traceId: "req_88291" },
    { id: 2, level: "info", source: "WhatsApp API", message: "Template 'welcome_v2' status updated to APPROVED", timestamp: "2024-12-01 10:40:05", traceId: "evt_99211" },
    { id: 3, level: "success", source: "Auth Service", message: "API Key pk_live_...9921 generated by Admin", timestamp: "2024-12-01 10:38:22", traceId: "audit_112" },
    { id: 4, level: "warning", source: "Retell AI", message: "Agent response latency high (1200ms)", timestamp: "2024-12-01 10:35:11", traceId: "trace_772" },
    { id: 5, level: "info", source: "System", message: "Daily backup completed successfully", timestamp: "2024-12-01 03:00:00", traceId: "sys_001" },
    { id: 6, level: "error", source: "Database", message: "Connection timeout retrying...", timestamp: "2024-12-01 02:59:55", traceId: "db_552" },
  ]);

  return (
    <div className="space-y-6 max-w-6xl mx-auto">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold tracking-tight flex items-center gap-2">
            <ScrollText className="h-6 w-6 text-muted-foreground" />
            System Logs
          </h2>
          <p className="text-muted-foreground">Real-time record of all system events, errors, and audit trails.</p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline">
            <Download className="h-4 w-4 mr-2" />
            Export CSV
          </Button>
          <Button variant="outline" size="icon">
            <RefreshCw className="h-4 w-4" />
          </Button>
        </div>
      </div>

      <Card className="bg-card/50 border-border/50">
        <CardHeader className="pb-3">
          <div className="flex items-center justify-between">
            <CardTitle>Event Stream</CardTitle>
            <div className="flex items-center gap-2">
              <div className="relative w-64">
                <Search className="absolute left-2 top-2.5 h-4 w-4 text-muted-foreground" />
                <Input placeholder="Search logs..." className="pl-8 h-9" />
              </div>
              <Button variant="outline" size="sm" className="h-9">
                <Filter className="h-3 w-3 mr-2" />
                Filter
              </Button>
            </div>
          </div>
        </CardHeader>
        <CardContent>
          <div className="rounded-md border border-border/50 overflow-hidden">
            <table className="w-full text-sm text-left">
              <thead className="bg-muted/50 text-muted-foreground font-medium">
                <tr>
                  <th className="px-4 py-3 w-[140px]">Timestamp</th>
                  <th className="px-4 py-3 w-[100px]">Level</th>
                  <th className="px-4 py-3 w-[140px]">Source</th>
                  <th className="px-4 py-3">Message</th>
                  <th className="px-4 py-3 w-[100px] text-right">Trace ID</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border/50">
                {logs.map((log) => (
                  <tr key={log.id} className="hover:bg-muted/30 transition-colors group">
                    <td className="px-4 py-3 font-mono text-xs text-muted-foreground whitespace-nowrap">
                      {log.timestamp}
                    </td>
                    <td className="px-4 py-3">
                      <Badge variant="outline" className={`
                        capitalize border-0 
                        ${log.level === 'error' ? 'bg-rose-500/10 text-rose-500' : 
                          log.level === 'warning' ? 'bg-amber-500/10 text-amber-500' : 
                          log.level === 'success' ? 'bg-emerald-500/10 text-emerald-500' : 
                          'bg-blue-500/10 text-blue-500'}
                      `}>
                        {log.level === 'error' && <AlertTriangle className="h-3 w-3 mr-1" />}
                        {log.level === 'success' && <CheckCircle className="h-3 w-3 mr-1" />}
                        {log.level === 'info' && <Info className="h-3 w-3 mr-1" />}
                        {log.level}
                      </Badge>
                    </td>
                    <td className="px-4 py-3 font-medium">{log.source}</td>
                    <td className="px-4 py-3 text-muted-foreground group-hover:text-foreground transition-colors">
                      {log.message}
                    </td>
                    <td className="px-4 py-3 text-right font-mono text-xs text-muted-foreground">
                      {log.traceId}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
